---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod1-pv
  labels:
    app: prod1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/prod1/data
    server: ec2-3-22-34-165.us-east-2.compute.amazonaws.com